spring:
  threads:
    virtual:
      enabled: true
  application:
    name: oidf-node
    version: '@project.version@'
server:
  port: 8000
  compression:
    enabled: true

logging:
  level:
    ROOT: INFO
    se.swedenconnect: INFO
openid:
  federation:
    storage: memory
    registry:
      integration:
        enabled: false

management:
  metrics:
    tags:
      application_version: ${spring.application.version}
      application_name: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"