spring:
  application:
    name: OidcFed.Services
server:
  port: 8000
  compression:
    enabled: true

logging:
  level:
    ROOT: INFO
    se.digg: INFO
openid:
  federation:
    resolver:
      active: false

    trust-anchor:
      active: false

    trust-mark-issuer:
      active: false
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"