spring:
  threads:
    virtual:
      enabled: true
  application:
    name: oidf-node
    version: '@project.version@'
server:
  port: 8000
  compression:
    enabled: true
  forward-headers-strategy: native

logging:
  structured:
    format:
      console: ecs
  level:
    ROOT: INFO
    se.swedenconnect: INFO
openid:
  federation:
    storage: memory
    registry:
      integration:
        enabled: false

management:
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
  metrics:
    tags:
      application_version: ${spring.application.version}
      application_name: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"