spring:
  application:
    name: OidcFed.Services
server:
  port: 8000
  compression:
    enabled: true

logging:
  level:
    ROOT: INFO
    se.digg: INFO
openid:
  federation:
    storage: memory
    registry:
      integration:
        enabled: false

management:
  prometheus:
    metrics:
      export:
        enabled: true
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"